branches:
  - main

tag_prefix: "v"

commit_pattern: '^(?P<type>\w+)(?:\((?P<scope>[^)]+)\))?(?P<breaking>!)?:\s+(?P<description>.+)'

breaking_section: Breaking Changes

types:
  - name: feat
    bump: minor
    section: Features
  - name: fix
    bump: patch
    section: Bug Fixes
  - name: perf
    bump: patch
    section: Bug Fixes
  - name: chore
  - name: docs
  - name: ci
  - name: refactor
  - name: test
  - name: build
  - name: style
  - name: revert

changelog:
  file: CHANGELOG.md

hooks:
  pre_release:
    - cargo check --workspace
    - cargo clippy --workspace -- -D warnings
    - cargo test --workspace
