name: "Semantic Release"
author: "urmzd"
description: "Automated semantic versioning and release management — single binary, zero-config, language-agnostic."

branding:
  icon: "upload-cloud"
  color: "green"

inputs:
  command:
    description: "The sr subcommand to run (release, plan, changelog, version, config)"
    required: false
    default: "release"
  dry-run:
    description: "Preview changes without executing them"
    required: false
    default: "false"
  force:
    description: "Re-release the current tag (use when a previous release partially failed)"
    required: false
    default: "false"
  config:
    description: "Path to the config file"
    required: false
    default: ".urmzd.sr.yml"
  github-token:
    description: "GitHub token for creating releases"
    required: false
    default: ${{ github.token }}
  git-user-name:
    description: "Git user name for tag creation"
    required: false
    default: "semantic-release[bot]"
  git-user-email:
    description: "Git user email for tag creation"
    required: false
    default: "semantic-release[bot]@urmzd.com"
  artifacts:
    description: "Glob patterns for artifact files to upload (newline or comma separated)"
    required: false
    default: ""
  build-command:
    description: "Shell command to run after version bump, before commit (SR_VERSION and SR_TAG env vars available)"
    required: false
    default: ""

outputs:
  version:
    description: "The released version (empty if no release)"
    value: ${{ steps.release.outputs.version }}
  previous-version:
    description: "The previous version before this release (empty if first release)"
    value: ${{ steps.release.outputs.previous_version }}
  tag:
    description: "The git tag created for this release (empty if no release)"
    value: ${{ steps.release.outputs.tag }}
  bump:
    description: "The bump level applied (major/minor/patch, empty if no release)"
    value: ${{ steps.release.outputs.bump }}
  floating-tag:
    description: "The floating major tag (e.g. v3, empty if disabled or no release)"
    value: ${{ steps.release.outputs.floating_tag }}
  commit-count:
    description: "Number of commits included in this release"
    value: ${{ steps.release.outputs.commit_count }}
  released:
    description: "Whether a release was created (true/false)"
    value: ${{ steps.release.outputs.released }}
  json:
    description: "Full release metadata as JSON (empty if no release)"
    value: ${{ steps.release.outputs.json }}

runs:
  using: "composite"
  steps:
    - name: Configure git identity
      shell: bash
      run: |
        git config user.name "${{ inputs.git-user-name }}"
        git config user.email "${{ inputs.git-user-email }}"

    - name: Download sr binary
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        set -euo pipefail

        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        case "$ARCH" in
          x86_64)  ARCH="x86_64" ;;
          aarch64|arm64) ARCH="aarch64" ;;
          *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
        esac

        case "$OS" in
          linux)  TARGET="${ARCH}-unknown-linux-musl" ;;
          darwin) TARGET="${ARCH}-apple-darwin" ;;
          *) echo "Unsupported OS: $OS"; exit 1 ;;
        esac

        BINARY_NAME="sr-${TARGET}"
        DOWNLOAD_URL="https://github.com/urmzd/semantic-release/releases/latest/download/${BINARY_NAME}"

        mkdir -p "$HOME/.local/bin"
        curl -sSfL "$DOWNLOAD_URL" -o "$HOME/.local/bin/sr"
        chmod +x "$HOME/.local/bin/sr"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - name: Run sr
      id: release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        set -uo pipefail
        ARGS=()
        ARGS+=("${{ inputs.command }}")
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          ARGS+=("--dry-run")
        fi
        if [ "${{ inputs.force }}" = "true" ]; then
          ARGS+=("--force")
        fi
        IFS=$'\n,' read -ra PATTERNS <<< "${{ inputs.artifacts }}"
        for pattern in "${PATTERNS[@]}"; do
          trimmed=$(echo "$pattern" | xargs)
          if [ -n "$trimmed" ]; then
            ARGS+=("--artifacts" "$trimmed")
          fi
        done

        if [ -n "${{ inputs.build-command }}" ]; then
          ARGS+=("--build-command" "${{ inputs.build-command }}")
        fi

        set +e
        JSON_OUTPUT=$(sr "${ARGS[@]}" | tail -1)
        EXIT_CODE=${PIPESTATUS[0]}
        set -e

        if [ "$EXIT_CODE" -eq 0 ]; then
          echo "json=${JSON_OUTPUT}" >> "$GITHUB_OUTPUT"
          echo "version=$(echo "$JSON_OUTPUT" | jq -r '.version')" >> "$GITHUB_OUTPUT"
          echo "previous_version=$(echo "$JSON_OUTPUT" | jq -r '.previous_version')" >> "$GITHUB_OUTPUT"
          echo "tag=$(echo "$JSON_OUTPUT" | jq -r '.tag')" >> "$GITHUB_OUTPUT"
          echo "bump=$(echo "$JSON_OUTPUT" | jq -r '.bump')" >> "$GITHUB_OUTPUT"
          echo "floating_tag=$(echo "$JSON_OUTPUT" | jq -r '.floating_tag')" >> "$GITHUB_OUTPUT"
          echo "commit_count=$(echo "$JSON_OUTPUT" | jq -r '.commit_count')" >> "$GITHUB_OUTPUT"
          echo "released=true" >> "$GITHUB_OUTPUT"
        elif [ "$EXIT_CODE" -eq 2 ]; then
          echo "No releasable changes found"
          echo "json=" >> "$GITHUB_OUTPUT"
          echo "version=" >> "$GITHUB_OUTPUT"
          echo "previous_version=" >> "$GITHUB_OUTPUT"
          echo "tag=" >> "$GITHUB_OUTPUT"
          echo "bump=" >> "$GITHUB_OUTPUT"
          echo "floating_tag=" >> "$GITHUB_OUTPUT"
          echo "commit_count=" >> "$GITHUB_OUTPUT"
          echo "released=false" >> "$GITHUB_OUTPUT"
        else
          echo "json=" >> "$GITHUB_OUTPUT"
          echo "version=" >> "$GITHUB_OUTPUT"
          echo "previous_version=" >> "$GITHUB_OUTPUT"
          echo "tag=" >> "$GITHUB_OUTPUT"
          echo "bump=" >> "$GITHUB_OUTPUT"
          echo "floating_tag=" >> "$GITHUB_OUTPUT"
          echo "commit_count=" >> "$GITHUB_OUTPUT"
          echo "released=false" >> "$GITHUB_OUTPUT"
          exit "$EXIT_CODE"
        fi
